name: Flaky tests using trunk.io

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  flaky:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Flaky test detection and upload to trunk.io
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload results to trunk.io
        # Run this step even if the test step ahead fails
        if: '!cancelled()'
        uses: trunk-io/analytics-uploader@main
        with:
          # Path to your test results.
          junit-paths: "**/*.xml"
          # Provide your Trunk organization slug.
          org-slug: shashank-priyadarshi
          # Provide your Trunk API token as a GitHub secret.
          token: "${{ secrets.TRUNK_API_TOKEN }}"
        continue-on-error: false
